import { CircleAlert } from "lucide-react";
import type { HistoricalContextMetric, WashoutSnapshot } from "../lib/reentry";

const finite=(v?:number|null)=>typeof v==="number"&&Number.isFinite(v);
const plain=(v?:number|null,d=1)=>finite(v)?Number(v).toFixed(d):"UNAVAILABLE";
const signed=(v?:number|null,d=1)=>finite(v)?`${Number(v)>0?"+":""}${Number(v).toFixed(d)}`:"UNAVAILABLE";
const percentile=(v?:number|null)=>finite(v)?`${Math.round(Number(v))}th percentile`:"Percentile unavailable";
const fresh=(kind:string,value?:string|null)=>`${kind} · ${value||"time unavailable"}`;

function spxaState(v?:number|null){if(!finite(v))return"UNAVAILABLE";if(Number(v)<10)return"EXTREME OVERSOLD";if(Number(v)<30)return"OVERSOLD";if(Number(v)<45)return"WEAK";if(Number(v)<=70)return"NORMAL";if(Number(v)<=90)return"STRONG";return"EXTREME OVERBOUGHT";}
function mmfdState(v?:number|null,s?:string|null){if(s)return s.replaceAll("_"," ");if(!finite(v))return"UNAVAILABLE";if(Number(v)<15)return"EXTREME OVERSOLD";if(Number(v)<30)return"OVERSOLD";if(Number(v)<=70)return"NORMAL";if(Number(v)<=85)return"STRONG";return"EXTREME OVERBOUGHT";}
function momentumState(v?:number|null){if(!finite(v))return"UNAVAILABLE";const x=Number(v);if(x<=-150)return"EXTREME NEGATIVE";if(x<=-100)return"STRETCHED NEGATIVE";if(x<-50)return"WEAK NEGATIVE";if(x<=50)return"NORMAL";if(x<100)return"STRONG POSITIVE";if(x<150)return"STRETCHED POSITIVE";return"EXTREME POSITIVE";}
function nasiState(v?:number|null){if(!finite(v))return"UNAVAILABLE";if(Number(v)<10)return"EXTREME OVERSOLD";if(Number(v)<20)return"VERY OVERSOLD";if(Number(v)<30)return"OVERSOLD";if(Number(v)>90)return"EXTREME OVERBOUGHT";if(Number(v)>80)return"VERY OVERBOUGHT";if(Number(v)>70)return"OVERBOUGHT";return"NORMAL";}
function volumeBreadthState(v?:number|null){if(!finite(v))return"UNAVAILABLE";const x=Number(v),a=Math.abs(x),side=x>=0?"BUYING":"SELLING";if(a<250)return"NORMAL / BALANCED";if(a<1000)return`MODERATE ${side}`;if(a<2500)return`STRONG ${side}`;return`EXTREME ${side}`;}
function ratioState(v?:number|null){if(!finite(v))return"UNAVAILABLE";const x=Number(v);if(x>=9)return"EXTREME SELLING";if(x>=4)return"HEAVY SELLING";if(x>=2)return"ELEVATED SELLING";if(x<=1/9)return"EXTREME BUYING";if(x<=.25)return"HEAVY BUYING";if(x<.5)return"ELEVATED BUYING";return"NORMAL / MIXED";}
function vvixState(v?:number|null,p?:number|null){if(finite(p)&&Number(p)>=95)return"EXTREME STRESS";if(!finite(v))return"UNAVAILABLE";const x=Number(v);if(x<70)return"EXTREME COMPLACENCY";if(x<80)return"CALM";if(x<=100)return"NORMAL";if(x<=120)return"ELEVATED STRESS";return"EXTREME STRESS";}
function liveSkewState(r?:number|null){if(!finite(r))return"UNAVAILABLE";const x=Number(r);if(x>=1.20)return"EXTREME DOWNSIDE SKEW";if(x>=1.10)return"STRETCHED DOWNSIDE SKEW";if(x>1.05)return"ELEVATED DOWNSIDE SKEW";if(x<.95)return"UPSIDE SKEW";return"NORMAL / BALANCED";}
function officialSkewState(v?:number|null,p?:number|null){if(finite(p)&&Number(p)>=95)return"EXTREME TAIL RISK";if(!finite(v))return"UNAVAILABLE";const x=Number(v);if(x>=150)return"EXTREME TAIL RISK";if(x>=140)return"HIGH TAIL RISK";if(x>=125)return"ELEVATED TAIL RISK";if(x>=110)return"NORMAL";return"LOW TAIL RISK";}
function stateClass(value:string){const v=value.toUpperCase();if(v.includes("EXTREME"))return"extreme-text";if(v.includes("BUYING")||v.includes("STRONG")||v.includes("CALM")||v.includes("LOW TAIL")||v==="NORMAL"||v.includes("NORMAL /"))return"good-text";if(v.includes("SELLING")||v.includes("HIGH TAIL"))return"bad-text";if(v.includes("OVERSOLD")||v.includes("STRETCHED")||v.includes("HEAVY")||v.includes("ELEVATED")||v.includes("WEAK"))return"warn";return"muted";}
function directionClass(value?:string|null){const v=(value||"").toUpperCase();if(["RISING","WIDENING","DETERIORATING"].includes(v))return"bad-text";if(["FALLING","NARROWING","IMPROVING","EASING","RELIEF"].includes(v))return"good-text";return"muted";}
function historyBenchmark(m:HistoricalContextMetric|undefined,fallback:string){if(!m)return fallback;if(m.reliable&&finite(m.percentile))return`${percentile(m.percentile)} of validated captured history · ${m.state||"NORMAL"}`;return`Working benchmark · ${fallback} · percentile history ${m.session_count??0}/${m.minimum_reliable_sessions??20} sessions`;}
function historyDetail(m:HistoricalContextMetric|undefined){if(!m)return undefined;if(m.reliable&&finite(m.percentile))return`${m.methodology||"Empirical captured history"} · ${m.history_start_date||"-"} to ${m.history_end_date||"-"}`;return`Percentile withheld until the reliability gate is met. ${m.methodology||"Captured history is still accumulating."}`;}
function historyState(m:HistoricalContextMetric|undefined,fallback:string){return m?.reliable&&m.state?m.state:fallback;}

function MetricCard({name,symbol,value,benchmark,state,direction,directionTone,interpretation,detail,behavior,behaviorExplanation,freshness}:{name:string;symbol:string;value:string;benchmark:string;state:string;direction?:string|null;directionTone?:string;interpretation:string;detail?:string;behavior:string;behaviorExplanation:string;freshness:string}){
 const dir=direction?.replaceAll("_"," ")||"DIRECTION UNAVAILABLE",tone=stateClass(state);return <div className="indicator-card" data-tone={tone}><div className="indicator-title"><div><b>{name}</b><small>{symbol}</small></div><span className="indicator-dot"/></div><strong className="indicator-value">{value}</strong><div className="indicator-badges"><span className={tone}>{state}</span><span className={directionTone||directionClass(direction)}>{dir}</span><span className="behavior-badge">{behavior}</span></div><div className="indicator-freshness">{freshness}</div><p className="plain-explain"><b>WHAT THIS MEANS</b>{interpretation}</p><p className="plain-explain behavior-copy"><b>HOW TO READ IT</b>{behaviorExplanation}</p><div className="indicator-reference"><b>BENCHMARK</b>{benchmark}</div>{detail?<div className="indicator-detail">{detail}</div>:null}</div>;
}

export default function ReentryDecisionDetails({washout}:{washout:WashoutSnapshot}){
 const u=washout.unified_engine,w=washout.values;if(!u||!w)return <section className="card section-card"><div className="notice"><CircleAlert size={16}/> RE-ENTRY ENGINE UNAVAILABLE</div></section>;
 const fast=u.fast_families||{FAST_BREADTH_TURN:washout.families?.fast_breadth_turn??false,MOMENTUM_TURN:washout.families?.momentum_turn??false,NET_VOLUME_TURN:washout.families?.net_volume_turn??false,DOWN_UP_RATIO_RELIEF:washout.families?.down_up_ratio_relief??false},context=u.context_support||{};
 const fastRows=[["Fast breadth",fast.FAST_BREADTH_TURN,"NO BREADTH TURN","Are more stocks starting to recover quickly after the selloff?"],["Breadth momentum",fast.MOMENTUM_TURN,"NO MOMENTUM TURN","Is the overall pace of improving stocks getting stronger rather than weaker?"],["Advance/decline volume",fast.NET_VOLUME_TURN,"NO VOLUME TURN","Is more trading volume flowing into advancing stocks than declining stocks?"],["Selling intensity relief",fast.DOWN_UP_RATIO_RELIEF,"NO RELIEF","Is heavy selling pressure easing enough to suggest sellers are losing control?"]] as const;
 const contextRows=[["MMFD improving",context.MMFD_IMPROVING,"NOT IMPROVING","Are more U.S. stocks getting back above their very short-term trend?"],["NASI+ turning upward",context.NASI_TURNING_UP,"NOT TURNING UP","Is broader Nasdaq participation beginning to turn up from a weak level?"],["VVIX easing",context.VVIX_EASING,"NOT EASING","Is fear inside the volatility market itself starting to calm down?"],["SKEW narrowing",context.SKEW_NARROWING,"NOT NARROWING","Is demand for crash protection becoming less extreme?"]] as const;
 const vvix=washout.vvix_live as any,skew=washout.skew_live as any,mmfd=washout.mmfd_live as any,hist=washout.historical_context?.metrics||{};const vvixChange=finite(vvix?.change_points_vs_prior_close)?vvix?.change_points_vs_prior_close:finite(w.VVIX)&&finite(w.VVIX_PRIOR_CLOSE)?Number(w.VVIX)-Number(w.VVIX_PRIOR_CLOSE):null;const vvixPct=vvix?.historical_percentile_2y??w.VVIX_PERCENTILE_2Y;const officialSkewPct=skew?.official_skew_percentile_2y??w.SKEW_OFFICIAL_PERCENTILE_2Y;const officialSkew=skew?.official_skew_latest_close??w.SKEW_OFFICIAL_CLOSE;const officialDate=skew?.official_skew_date||"date unavailable";const liveSkew=skew?.live_proxy_vol_points??w.SKEW_LIVE_PROXY;const liveSkewRatio=skew?.live_proxy_ratio??w.SKEW_LIVE_PROXY_RATIO;const liveSkewMode=skew?.source_mode||"SOURCE MODE UNAVAILABLE";const snapshotTime=u.timestamp_et||washout.snapshot_generated_at_et||w.timestamp_et||"UNAVAILABLE";const marketDate=(u as any).market_date||(w as any).market_date||"prior completed session";
 return <><style>{`
 body{background:radial-gradient(circle at 18% -8%,rgba(47,118,80,.10),transparent 28%),radial-gradient(circle at 91% 4%,rgba(163,116,42,.07),transparent 24%),var(--bg)}.card{box-shadow:0 16px 42px rgba(28,40,32,.065);border-color:#d8d4c9}.family-section{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:14px 0 20px}.family-panel{border:1px solid var(--line);border-radius:16px;padding:14px;background:linear-gradient(180deg,rgba(255,255,255,.58),rgba(255,255,255,.24));box-shadow:0 9px 24px rgba(30,42,33,.035)}.family-panel h3{margin:0 0 10px;font-size:13px}.family-row{display:grid;grid-template-columns:1fr auto;gap:4px 12px;padding:10px 0;border-top:1px solid var(--line);font-size:11px}.family-row:first-of-type{border-top:0}.family-row b{font-size:8px;letter-spacing:.045em;border-radius:999px;padding:5px 7px;border:1px solid var(--line);background:rgba(255,255,255,.55);align-self:start}.family-copy{grid-column:1/2;font-size:9px;line-height:1.4;color:var(--muted)}
 .indicator-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.indicator-card{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:16px;padding:16px;background:linear-gradient(180deg,rgba(255,255,255,.66),rgba(255,255,255,.30));box-shadow:0 8px 24px rgba(31,44,35,.035)}.indicator-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:#aaa}.indicator-card[data-tone="good-text"]:before{background:var(--green)}.indicator-card[data-tone="warn"]:before{background:var(--amber)}.indicator-card[data-tone="bad-text"]:before{background:var(--red)}.indicator-card[data-tone="extreme-text"]:before{background:linear-gradient(var(--red),var(--amber))}.indicator-title{display:flex;justify-content:space-between;gap:10px}.indicator-title b{font-size:11px}.indicator-title small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.indicator-dot{width:8px;height:8px;border-radius:50%;background:#bbb}.indicator-value{display:block;font-size:26px;margin:10px 0 8px;letter-spacing:-.035em}.indicator-badges{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:6px}.indicator-badges span{border:1px solid currentColor;border-radius:999px;padding:4px 7px;font-size:8px;font-weight:900;letter-spacing:.045em;background:rgba(255,255,255,.45)}.behavior-badge{color:#5d625b}.indicator-freshness{font-size:8px;font-weight:850;letter-spacing:.035em;color:#5c615a;margin-bottom:8px}.plain-explain{font-size:10px;line-height:1.5;margin:8px 0 10px;color:#3f443d}.plain-explain b{display:block;font-size:7px;letter-spacing:.1em;color:var(--muted);margin-bottom:2px}.behavior-copy{background:rgba(163,116,42,.055);padding:8px;border-radius:8px}.indicator-reference{font-size:9px;line-height:1.48;color:#50554e;padding:9px 10px;border-radius:9px;background:#f0eee8}.indicator-reference b{display:block;margin-bottom:2px;font-size:7px;letter-spacing:.12em;color:var(--muted)}.indicator-detail{font-size:9px;line-height:1.45;color:var(--muted);margin-top:6px}.engine-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.engine-meta span{font-size:9px;color:var(--muted);border:1px solid var(--line);border-radius:999px;padding:6px 8px;background:rgba(255,255,255,.45)}.extreme-text{color:#b75f34}.warn{color:var(--amber)}@media(max-width:900px){.indicator-grid{grid-template-columns:1fr 1fr}}@media(max-width:680px){.family-section,.indicator-grid{grid-template-columns:1fr}}
 `}</style>
 <section className="card section-card"><div className="section-heading"><div><span className="kicker">REVERSAL EVIDENCE</span><h2>What has actually turned?</h2></div></div><div className="family-section"><div className="family-panel"><h3>Fast reversal families · {u.fast_family_count??0}/4</h3>{fastRows.map(([name,on,off,explain])=><div className="family-row" key={name}><span>{name}</span><b className={on?"good-text":"muted"}>{on?"TURNED":off}</b><span className="family-copy">{explain}</span></div>)}</div><div className="family-panel"><h3>Context support · {u.context_support_count??0}/4</h3>{contextRows.map(([name,on,off,explain])=><div className="family-row" key={name}><span>{name}</span><b className={on?"good-text":"muted"}>{on?"CONFIRMED":off}</b><span className="family-copy">{explain}</span></div>)}</div></div><div className="engine-meta"><span>Oversold setup: {u.oversold_gate?"YES":"NO"}</span><span>Data quality: {u.data_quality_status||washout.data_quality?.status||"UNAVAILABLE"}</span><span>Snapshot: {snapshotTime}</span></div></section>
 <section className="card section-card"><div className="section-heading"><div><span className="kicker">INDICATOR DETAIL</span><h2>Current level vs. intelligent benchmark</h2></div></div><p className="section-intro">Each indicator shows its state, whether it is contrarian or confirming, a retail explanation, and exactly how fresh the underlying reading is.</p><div className="indicator-grid">
 <MetricCard name="S&P 500 above 20-day average" symbol="SPXA20R" value={`${plain(w.SPXA20R,1)}%`} benchmark="<10 extreme oversold · 10–30 oversold · 30–45 weak · 45–70 normal · 70–90 strong · >90 extreme overbought" state={spxaState(w.SPXA20R)} direction={fast.FAST_BREADTH_TURN?"IMPROVING":"NO BREADTH TURN"} behavior="CONTRARIAN SETUP" behaviorExplanation="Very low breadth is a contrarian setup because widespread weakness can become exhausted. It is not bullish by itself; the turn upward is the confirmation." freshness={fresh("INTRADAY SNAPSHOT",(w as any).SPXA20R_TIMESTAMP_ET||snapshotTime)} interpretation="How many S&P 500 stocks are still above their short-term trend. Very low readings mean weakness is widespread and the market is stretched."/>
 <MetricCard name="U.S. stocks above 5-day average" symbol="MMFD" value={`${plain(w.MMFD,1)}%`} benchmark="<15 extreme oversold · 15–30 oversold · 30–70 normal zone centered near 50 · 70–85 strong · >85 extreme overbought" state={mmfdState(w.MMFD,w.MMFD_STATE)} direction={context.MMFD_IMPROVING?"IMPROVING":"NOT IMPROVING"} behavior="CONTRARIAN + CONFIRMING" behaviorExplanation="A very low level is contrarian; improvement from that low becomes confirming evidence that participation is recovering." freshness={fresh("INTRADAY SNAPSHOT",mmfd?.timestamp_et||snapshotTime)} detail={`Universe ${mmfd?.universe_size??"-"} · valid ${mmfd?.valid_5d_observations??"-"} · coverage ${finite(mmfd?.coverage_pct)?`${plain(mmfd?.coverage_pct,1)}%`:"UNAVAILABLE"}`} interpretation="How many U.S. stocks are back above their very short-term 5-day trend. Rising from a low level means participation in the bounce is spreading."/>
 <MetricCard name="NYSE breadth momentum" symbol="NYMO" value={signed(w.NYMO,1)} benchmark={historyBenchmark(hist.NYMO,"0 neutral · ±50 normal band · ±100 stretched · ±150 classic extended/extreme reference")} state={historyState(hist.NYMO,momentumState(w.NYMO))} direction={fast.MOMENTUM_TURN?"IMPROVING":"NO MOMENTUM TURN"} behavior="CONTRARIAN AT EXTREMES" behaviorExplanation="Deep negative readings can mark exhaustion, but the actionable confirmation is momentum turning upward from the extreme." freshness={fresh("DAILY CLOSE",hist.NYMO?.history_end_date||marketDate)} detail={historyDetail(hist.NYMO)} interpretation="Measures whether NYSE stocks are collectively gaining or losing momentum. Deep negatives mean broad weakness; a turn upward means that weakness may be starting to reverse."/>
 <MetricCard name="Nasdaq breadth momentum" symbol="NAMO" value={signed(w.NAMO,1)} benchmark={historyBenchmark(hist.NAMO,"0 neutral · ±50 normal band · ±100 stretched · ±150 extended/extreme reference")} state={historyState(hist.NAMO,momentumState(w.NAMO))} direction={fast.MOMENTUM_TURN?"IMPROVING":"NO MOMENTUM TURN"} behavior="CONTRARIAN AT EXTREMES" behaviorExplanation="Deeply negative Nasdaq breadth can be a contrarian setup. A turn higher is what converts that setup into recovery evidence." freshness={fresh("DAILY CLOSE",hist.NAMO?.history_end_date||marketDate)} detail={historyDetail(hist.NAMO)} interpretation="Same idea as NYMO, but for Nasdaq stocks. It tells us whether weakness or recovery is spreading across the Nasdaq rather than just the big indexes."/>
 <MetricCard name="Nasdaq summation RSI" symbol="NASI+" value={plain(w.NASI_RSI,1)} benchmark="<30 oversold · <20 very oversold · <10 extreme · 30–70 normal · >70 overbought · >90 extreme" state={nasiState(w.NASI_RSI)} direction={w.NASI_DIRECTION} directionTone={w.NASI_DIRECTION==="FALLING"?"bad-text":w.NASI_DIRECTION==="RISING"?"good-text":undefined} behavior="CONTRARIAN + CONFIRMING" behaviorExplanation="Oversold is contrarian context; a rising NASI+ is confirmation that the broader Nasdaq recovery is becoming more durable." freshness={fresh("DAILY / PRIOR COMPLETED CLOSE",marketDate)} detail={finite(w.NASI_EMA10)?`EMA10 ${plain(w.NASI_EMA10,1)}`:undefined} interpretation="A slower Nasdaq breadth gauge. Low readings mean participation has been weak for a while; turning upward helps confirm that the recovery is becoming more durable."/>
 <MetricCard name="NYSE advance/decline volume" symbol="NYUD" value={signed(w.NYUD,1)} benchmark={historyBenchmark(hist.NYUD,"0 balance · working feed scale: |value| <250 normal, 250–1,000 moderate, 1,000–2,500 strong, >2,500 extreme")} state={historyState(hist.NYUD,volumeBreadthState(w.NYUD))} direction={fast.NET_VOLUME_TURN?"IMPROVING":"NO VOLUME TURN"} behavior="CONFIRMING" behaviorExplanation="This is confirming: positive/rising buying volume supports the idea that the rebound has real participation behind it." freshness={fresh("INTRADAY",(w as any).NYUD_TIMESTAMP_ET||snapshotTime)} detail={historyDetail(hist.NYUD)} interpretation="Shows whether more NYSE trading volume is flowing into stocks going up or stocks going down. Positive readings mean buyers are winning the volume battle."/>
 <MetricCard name="Nasdaq advance/decline volume" symbol="NAUD" value={signed(w.NAUD,1)} benchmark={historyBenchmark(hist.NAUD,"0 balance · working feed scale: |value| <250 normal, 250–1,000 moderate, 1,000–2,500 strong, >2,500 extreme")} state={historyState(hist.NAUD,volumeBreadthState(w.NAUD))} direction={fast.NET_VOLUME_TURN?"IMPROVING":"NO VOLUME TURN"} behavior="CONFIRMING" behaviorExplanation="This is confirming: stronger positive volume breadth means buyers are taking control across more Nasdaq stocks." freshness={fresh("INTRADAY",(w as any).NAUD_TIMESTAMP_ET||snapshotTime)} detail={historyDetail(hist.NAUD)} interpretation="Shows whether Nasdaq trading volume favors advancing or declining stocks. Strong positive readings mean the rebound has real buying volume behind it."/>
 <MetricCard name="NYSE down/up volume ratio" symbol="NYSE D/U" value={finite(w.nyse_down_up_ratio)?`${plain(w.nyse_down_up_ratio,2)}x`:"UNAVAILABLE"} benchmark={historyBenchmark(hist.nyse_down_up_ratio,"1.0x balance · 2x elevated selling · 4x heavy · 9x classic washout extreme; inverse bands flag buying dominance")} state={historyState(hist.nyse_down_up_ratio,ratioState(w.nyse_down_up_ratio))} direction={fast.DOWN_UP_RATIO_RELIEF?"RELIEF":"NO RELIEF"} behavior="CONTRARIAN AT EXTREMES" behaviorExplanation="Very high selling ratios can mark panic/exhaustion. The confirmation is the ratio collapsing back down as selling pressure eases." freshness={fresh("INTRADAY",snapshotTime)} detail={historyDetail(hist.nyse_down_up_ratio)} interpretation="Compares selling volume with buying volume on the NYSE. Above 1 means sellers dominate; well below 1 means buyers dominate; very high readings can mark panic selling."/>
 <MetricCard name="Nasdaq down/up volume ratio" symbol="NASDAQ D/U" value={finite(w.nasdaq_down_up_ratio)?`${plain(w.nasdaq_down_up_ratio,2)}x`:"UNAVAILABLE"} benchmark={historyBenchmark(hist.nasdaq_down_up_ratio,"1.0x balance · 2x elevated selling · 4x heavy · 9x classic washout extreme; inverse bands flag buying dominance")} state={historyState(hist.nasdaq_down_up_ratio,ratioState(w.nasdaq_down_up_ratio))} direction={fast.DOWN_UP_RATIO_RELIEF?"RELIEF":"NO RELIEF"} behavior="CONTRARIAN AT EXTREMES" behaviorExplanation="Panic-level selling can be contrarian, but the useful recovery evidence is relief: the selling ratio falls sharply as buyers return." freshness={fresh("INTRADAY",snapshotTime)} detail={historyDetail(hist.nasdaq_down_up_ratio)} interpretation="Same selling-versus-buying volume test for Nasdaq stocks. Falling ratios show selling pressure is easing and buyers are taking more control."/>
 <MetricCard name="Volatility of VIX" symbol="VVIX" value={plain(w.VVIX,1)} benchmark={`Working level scale: <70 extreme complacency · 70–80 calm · 80–100 normal · 100–120 elevated · >120 extreme stress · 2Y ${percentile(vvixPct)}`} state={vvix?.state||w.VVIX_STATE||vvixState(w.VVIX,vvixPct)} direction={vvix?.direction_vs_prior_close||w.VVIX_DIRECTION} behavior="CONTRARIAN STRESS GAUGE" behaviorExplanation="High VVIX can mark fear/exhaustion, but that is only the setup. Falling VVIX is the confirming sign that volatility fear is actually easing." freshness={fresh("INTRADAY",vvix?.timestamp_et||snapshotTime)} detail={`Prior close ${plain(vvix?.prior_close??w.VVIX_PRIOR_CLOSE,1)} · change ${signed(vvixChange,1)} pts`} interpretation="Measures fear about how volatile the VIX itself may become. High/rising VVIX means stress is intensifying; falling VVIX means volatility fear is calming."/>
 <MetricCard name="Live SPX downside skew proxy" symbol="25Δ PUT IV / CALL IV" value={finite(liveSkew)?`${plain(liveSkew,2)} vol pts`:"UNAVAILABLE"} benchmark="Working ratio scale: 0.95–1.05 balanced · 1.05–1.10 elevated downside skew · 1.10–1.20 stretched · >1.20 extreme" state={liveSkewState(liveSkewRatio)} direction={skew?.direction_vs_prior_snapshot||w.SKEW_DIRECTION||"NO CHANGE SIGNAL"} behavior="CONTRARIAN STRESS GAUGE" behaviorExplanation="Extreme downside hedging demand can be contrarian, but narrowing skew is the stronger confirmation that immediate crash fear is retreating." freshness={fresh("INTRADAY",skew?.timestamp_et||snapshotTime)} detail={`Ratio ${finite(liveSkewRatio)?plain(liveSkewRatio,2):"UNAVAILABLE"} · source ${liveSkewMode}`} interpretation="Shows how much more investors are paying for downside protection than upside exposure right now. Narrowing skew means immediate crash fear is easing."/>
 <MetricCard name="Official Cboe SKEW" symbol="SKEW" value={plain(officialSkew,1)} benchmark={`100 ≈ normal-distribution baseline · 125–140 elevated · 140–150 high · >150 extreme · 2Y ${percentile(officialSkewPct)}`} state={officialSkewState(officialSkew,officialSkewPct)} direction={skew?.official_skew_direction} behavior="CONTRARIAN / CONTEXTUAL" behaviorExplanation="High tail-risk pricing can reflect fear, but official SKEW is not a standalone buy signal. It is context; easing from an extreme is more useful for confirmation." freshness={fresh("DAILY CLOSE",officialDate)} detail={`Latest official date ${officialDate}`} interpretation="Cboe's official measure of how much rare, large downside moves are being priced into options. Higher readings mean investors are paying more for tail-risk protection."/>
 </div></section></>;
}
